app:
  name: vproapp
  replicaCount: 3

  containerPort: 8080

  image:
    repository: vprocontainers/vprofileapp
    tag: latest
    pullPolicy: Always

db:
  serviceName: vprodb

memcached:
  serviceName: vprocache01
